name: Ghost Cloudinary Docker Image CI

on:
  schedule:
    - cron: 0 9 * * *
  push:
    branches:
    - main
    - release/*

jobs:
  Main-Job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker login
      env:
        DH_UNAME: ${{ secrets.DH_UNAME }}
        DH_AT: ${{ secrets.DH_AT }}
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker login -u $DH_UNAME -p $DH_AT
        docker buildx create --use

    - name: Build the Docker image
      env:
        DH_UNAME: ${{ secrets.DH_UNAME }}
      run: |
        docker pull $DH_UNAME/ghost-cloudinary:latest || :
        docker buildx build --push --platform linux/arm64/v8,linux/amd64 --cache-from $DH_UNAME/ghost-cloudinary:latest --pull --file Dockerfile --tag $DH_UNAME/ghost-cloudinary:latest .

  Ping-Success:
    runs-on: ubuntu-latest
    needs: [Main-Job]
    steps:
      - run: curl -m 10 --retry 5 ${{ secrets.HEALTHCHECKS_DIMOV }}

  Ping-Failure:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [Main-Job]
    steps:
      - run: curl -m 10 --retry 5 ${{ secrets.HEALTHCHECKS_DIMOV }}/fail
